"""Read alpha to measure sprite rectangles; never modify the source images.

Find low-occupancy gutters instead of assuming a uniform slice. Emit runtime
UV/ground-anchor metadata and a QA report. Original generated alpha is preserved.
"""
raise SystemExit('This source-only crop workflow is retired. Run Tools/repack_mara.py instead.')
from pathlib import Path
import json
import numpy as np
from PIL import Image
from inspect_mara_components import components

root=Path(__file__).resolve().parents[1]
directions=['N','NE','E','SE','S','SW','W','NW']
records=[]
for direction in directions:
    img=Image.open(root/'ArtSource/MaraVey/v1'/f'Mara_{direction}.png').convert('RGBA')
    rgba=np.array(img); alpha=rgba[:,:,3]; h,w=alpha.shape
    assert alpha[0,0]==0, 'Opaque backdrop'
    sprites=sorted(components(alpha),key=lambda b:(b[2]+b[4])/2)
    assert len(sprites)==36,(direction,len(sprites))
    rows=[]
    frames=[]
    for action in range(6):
        row=sorted(sprites[action*6:action*6+6],key=lambda b:(b[1]+b[3])/2)
        for frame in range(6):
            _,x0,y0,x1,y1=row[frame]
            x0=max(0,x0-1);y0=max(0,y0-1);x1=min(w,x1+1);y1=min(h,y1+1)
            # Pelvis-area median excludes the narrow staff and broad coat tails.
            bh=y1-y0
            band=alpha[y0+int(bh*.48):y0+int(bh*.66),x0:x1]
            by,bx=np.where(band>160)
            px=x0+float(np.median(bx)) if len(bx) else (x0+x1)/2
            if action==4: px=(x0+x1)/2
            frames.append(dict(rect=[x0,y0,x1-x0,y1-y0],pivot=[round(px-x0,2),y1-y0-2],action=action,frame=frame))
    scale=112/float(np.median([f['rect'][3] for f in frames[:6]]))
    records.append(dict(direction=direction,width=w,height=h,scale=scale,rows=rows,frames=frames))
header=['#pragma once','// Generated by Tools/measure_mara.py; source pixels are not altered.','namespace MaraArt {','struct Frame { float X,Y,W,H,PX,PY; };','inline constexpr const TCHAR* Names[]={'+','.join('TEXT("Mara_'+d+'")' for d in directions)+'};','inline constexpr float Scale[]={'+','.join(f'{r["scale"]:.6f}f' for r in records)+'};','inline constexpr Frame Frames[8][36]={']
for record in records:
    header.append('{'+','.join('{'+','.join(f'{v:.2f}f' for v in f['rect']+f['pivot'])+'}' for f in record['frames'])+'},')
header+=['};','}']
(root/'Source/AnEmberRemains/MaraArtMetrics.h').write_text('\n'.join(header)+'\n')
(root/'ArtSource/MaraVey/v1/frames.json').write_text(json.dumps(records,indent=2)+'\n')
print(json.dumps([dict(direction=r['direction'],rows=r['rows'],scale=r['scale'],frames=len(r['frames'])) for r in records],indent=2))
