"""User-approved lossless sprite isolation/repacking. Originals stay untouched.
Keep each connected figure and its original three-pixel antialias fringe.
Discard neighboring figures/debris and translate into padded cells. No source
resampling, recoloring or mirroring. Resizing is only used for QA previews.
"""
from pathlib import Path
import json, hashlib
import numpy as np
from PIL import Image, ImageDraw
from inspect_mara_components import components
root=Path(__file__).resolve().parents[1]
source=root/'ArtSource/MaraVey/v1'
output=source/'Clean'
output.mkdir(exist_ok=True)
directions=['N','NE','E','SE','S','SW','W','NW']
cw,ch=384,320
anchor=(192,292)
records=[]
previews=[]
for direction in directions:
    path=source/f'Mara_{direction}.png'
    source_hash=hashlib.sha256(path.read_bytes()).hexdigest()
    rgba=np.array(Image.open(path).convert('RGBA'));alpha=rgba[:,:,3];h,w=alpha.shape
    found,labels=components(alpha,True)
    sprites=sorted(found,key=lambda b:(b[2]+b[4])/2)
    assert len(sprites)==36,(direction,len(sprites))
    owners=np.where(np.isin(labels,[s[5] for s in sprites]),labels,0)
    for step in range(3):
        old=owners.copy()
        for dy,dx in ((-1,0),(1,0),(0,-1),(0,1),(-1,-1),(-1,1),(1,-1),(1,1)):
            shifted=np.roll(old,(dy,dx),(0,1))
            if dy<0:shifted[dy:]=0
            if dy>0:shifted[:dy]=0
            if dx<0:shifted[:,dx:]=0
            if dx>0:shifted[:,:dx]=0
            take=(owners==0)&(shifted!=0)
            owners[take]=shifted[take]
    atlas=Image.new('RGBA',(cw*6,ch*6))
    frames=[]
    for action in range(6):
        row=sorted(sprites[action*6:action*6+6],key=lambda b:(b[1]+b[3])/2)
        for frame,comp in enumerate(row):
            count,x0,y0,x1,y1,label=comp
            keep=(owners==label)&(alpha>0)
            ys,xs=np.where(keep)
            left,top,right,bottom=int(xs.min()),int(ys.min()),int(xs.max())+1,int(ys.max())+1
            pixels=rgba[top:bottom,left:right].copy()
            mask=keep[top:bottom,left:right]
            pixels[~mask]=0
            bh=bottom-top
            band=pixels[int(bh*.48):int(bh*.66),:,3]
            by,bx=np.where(band>160)
            px=round(float(np.median(bx))) if len(bx) else (right-left)//2
            if action==4:px=(right-left)//2
            py=bh-2
            dx,dy=anchor[0]-px,anchor[1]-py
            assert dx>=8 and dy>=8 and dx+right-left<=cw-8 and dy+bh<=ch-8,(direction,action,frame,'padding')
            atlas.paste(Image.fromarray(pixels),(frame*cw+dx,action*ch+dy))
            assert np.array_equal(pixels[mask],rgba[top:bottom,left:right][mask])
            frames.append(dict(rect=[frame*cw,action*ch,cw,ch],pivot=list(anchor),action=action,frame=frame,sourceRect=[left,top,right-left,bh],sourcePivot=[px,py],retainedPixels=int(mask.sum())))
    scale=112/float(np.median([f['sourceRect'][3] for f in frames[:6]]))
    atlas.save(output/f'Mara_{direction}.png')
    assert hashlib.sha256(path.read_bytes()).hexdigest()==source_hash
    records.append(dict(direction=direction,width=cw*6,height=ch*6,scale=scale,sourceSHA256=source_hash,frames=frames))
    previews.append(atlas)
header=['#pragma once','// Generated by Tools/repack_mara.py; isolated, padded sprites.','namespace MaraArt {','struct Frame { float X,Y,W,H,PX,PY; };',f'inline constexpr int SheetWidth={cw*6},SheetHeight={ch*6};','inline constexpr const TCHAR* Names[]={'+','.join('TEXT("Mara_'+d+'")' for d in directions)+'};','inline constexpr float Scale[]={'+','.join(f'{r["scale"]:.6f}f' for r in records)+'};','inline constexpr Frame Frames[8][36]={']
for record in records:
    header.append('{'+','.join('{'+','.join(f'{v:.2f}f' for v in f['rect']+f['pivot'])+'}' for f in record['frames'])+'},')
header+=['};','}']
(root/'Source/AnEmberRemains/MaraArtMetrics.h').write_text('\n'.join(header)+'\n')
(source/'frames.json').write_text(json.dumps(records,indent=2)+'\n')
actions=['Idle','Walk','Run','Dodge','Roll','Cast']
movie=[]
for f in range(6):
    board=Image.new('RGB',(1280,880),(18,24,28));draw=ImageDraw.Draw(board)
    for a,name in enumerate(actions):draw.text((120+a*190,8),name,fill='white')
    for d,atlas in enumerate(previews):
        draw.text((10,64+d*104),directions[d],fill=(150,220,210))
        for a in range(6):
            cell=atlas.crop((f*cw,a*ch,(f+1)*cw,(a+1)*ch))
            s=records[d]['scale']*.78
            tile=cell.resize((round(cw*s),round(ch*s)),Image.Resampling.LANCZOS)
            board.paste(tile,(round(142+a*190-anchor[0]*s),round(119+d*104-anchor[1]*s)),tile)
    board.save(output/f'Contact-{f}.png');movie.append(board)
movie[0].save(output/'Animation-review.gif',save_all=True,append_images=movie[1:],duration=140,loop=0)
(output/'QA.json').write_text(json.dumps(dict(sheets=8,frames=288,originalsUnchanged=True,losslessRetainedPixels=True,minimumPadding=8,atlasSize=[cw*6,ch*6]),indent=2)+'\n')
print('MARA_REPACK_PASS: 8 atlases / 288 isolated padded frames; source hashes unchanged')
